name: Build Linux Image Template
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: "Name of main tag and workflow file."
      tags:
        type: string
        required: false
        description: "Extra tags to use besides main tag."

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
#      - uses: e1himself/goss-installation-action@v1.0.3
      - uses: e1himself/goss-installation-action@v1.0.4
        with:
          version: "v0.3.20"
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -t honestventures/steamcmd-linux-wine:${{ inputs.name }} .
        working-directory: dockerfiles/${{ inputs.name }}
      - name: Test Image
        run: dgoss run honestventures/steamcmd-linux-wine:${{ inputs.name }} --entrypoint=""

      # master
      - name: Tag Image
        run: >
          for TAG in ${{ inputs.tags }};
          do
            docker tag honestventures/steamcmd-linux-wine:${{ inputs.name }} honestventures/steamcmd-linux-wine:${TAG};
          done
        if: ${{ (github.ref == 'refs/heads/master') && (inputs.tags != '') }}
      - name: Push Image
        run: docker push steamcmd/steamcmd --all-tags
        if: ${{ github.ref == 'refs/heads/master' }}
